FROM openjdk:17-jdk-slim AS builder

RUN apt-get update && \
    apt-get install -y curl tar && \
    curl -o /tmp/maven.tar.gz https://downloads.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz && \
    tar -xzf /tmp/maven.tar.gz -C /opt && \
    ln -s /opt/apache-maven-3.8.6/bin/mvn /usr/bin/mvn && \
    rm -f /tmp/maven.tar.gz && \
    apt-get remove -y curl tar && \
    apt-get autoremove -y && \
    rm -rf /EXPOSE 8081

CMD ["java", "-jar", "users-api.jar"]
